# Frame object

Just like cpptraj, Frame object is work-horse of pytraj. 

In [51]:
from __future__ import print_function
from pytraj import io as mdio
from pytraj import Frame

In [52]:
# loading traj file to FrameArray object
traj = mdio.load("../tests/data/md1_prod.Tc5b.x", "../tests/data/Tc5b.top")

In [53]:
# get frame object
frame0 = traj[0]

# frame0 behaves like 2D array with shape of (n_atoms, 3)
print (frame0.shape)

(304, 3)


In [54]:
# fancy indexing
# whole coords
frame0[:][0]

array([-16.492,  12.434, -11.018])

In [55]:
# or
frame0[0, :]

array([-16.492,  12.434, -11.018])

In [56]:
# use numpy array as memory view for Frame object
import numpy as np

arr0 = np.asarray(frame0[:])

# update arr0 will update frame coords
print frame0[0, 0]
arr0[0, 0] = 1000.
print (frame0[0, 0])

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-56-78b4d70f128a>, line 7)

In [57]:
# extracting Frame coords with given mask. 
# 1st way

print (frame0[traj.top("@CA")])

[[-17.146  12.069  -9.756]
 [-15.774   9.648  -7.087]
 [-16.761   7.688  -3.829]
 [-15.228   5.335  -1.254]
 [-15.974   4.229   2.418]
 [-14.016   1.006   2.992]
 [-12.158  -1.711   1.129]
 [-10.459  -5.137   2.023]
 [ -9.524  -7.464  -0.965]
 [ -8.858 -11.163  -0.287]
 [ -7.71  -12.693   3.106]
 [ -5.13  -11.608   5.838]
 [ -1.73   -9.971   5.185]
 [  1.379  -9.977   7.51 ]
 [  4.659  -7.949   7.677]
 [  8.367  -8.606   6.79 ]
 [ 11.671  -7.68    8.742]
 [ 12.513  -3.997   8.439]
 [ 15.912  -2.833   6.877]
 [ 19.12   -3.114   8.925]]


In [58]:
# 2nd way
# need to set Topology for frame to use AtomMask
frame0.set_top(traj.top)
frame0["@CA"]

array([[-17.146,  12.069,  -9.756],
       [-15.774,   9.648,  -7.087],
       [-16.761,   7.688,  -3.829],
       [-15.228,   5.335,  -1.254],
       [-15.974,   4.229,   2.418],
       [-14.016,   1.006,   2.992],
       [-12.158,  -1.711,   1.129],
       [-10.459,  -5.137,   2.023],
       [ -9.524,  -7.464,  -0.965],
       [ -8.858, -11.163,  -0.287],
       [ -7.71 , -12.693,   3.106],
       [ -5.13 , -11.608,   5.838],
       [ -1.73 ,  -9.971,   5.185],
       [  1.379,  -9.977,   7.51 ],
       [  4.659,  -7.949,   7.677],
       [  8.367,  -8.606,   6.79 ],
       [ 11.671,  -7.68 ,   8.742],
       [ 12.513,  -3.997,   8.439],
       [ 15.912,  -2.833,   6.877],
       [ 19.12 ,  -3.114,   8.925]])

In [59]:
# coords of 11-th residue (index starts from 0)
frame0[":10"]

array([[ -9.386,  -9.873,  -0.657],
       [-10.344,  -9.807,  -0.969],
       [ -8.858, -11.163,  -0.287],
       [ -9.514, -11.931,  -0.696],
       [ -7.851, -11.243,  -0.697],
       [ -8.742, -11.387,   1.292],
       [ -9.38 , -10.654,   2.081]])

In [60]:
# indices of atoms in 10-th residue
traj.top(":10").selected_indices()

array('i', [169, 170, 171, 172, 173, 174, 175])

In [61]:
# TODO : double-check
print (traj.top[169].resnum)
print (frame0[169, :])

9
[-9.386 -9.873 -0.657]


In [62]:
# do basic math with Frame object (you can use numpy memory (as demonstated before))

print (frame0[12, :])
frame0 += frame0
print (frame0[12, :])

[-21.025  14.293 -10.013]
[-42.05   28.586 -20.026]


In [63]:
# calculate rmsd between two frames (2-th frame and 9-th frame in traj object)

print (traj[2].rmsd(traj[9]))

5.82364553553651


In [64]:
# methods / properties
print (dir(frame0))

['VCenterOfMass', 'VGeometricCenter', '__class__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__isub__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__pyx_vtable__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', 'add_by_mask', 'append_vec3', 'append_xyz', 'atoms', 'box_crd', 'boxview', 'buffer1d', 'buffer2d', 'calc_angle', 'calc_dihedral', 'calc_distance', 'calc_inertia', 'calc_temperature', 'center_on_origin', 'check_coords_invalid', 'clear_atoms', 'coords', 'copy', 'dist_rmsd', 'divide', 'fit_to', 'frame_iter', 'get_box', 'get_subframe', 'get_top', 'has_box', 'has_vel', 'i_address', 'info', 'is_empty', 'mass', 'n_atoms', 'n_repdims', 'neg_translate', 'py_free_mem', 'rmsd', 'rmsd_centered_ref', 'rmsd_nofit', 'rota

## Perform cpptraj Action on Frame object

In [65]:
# this code shows how we're able control workflow of cpptraj.
from pytraj import allactions
radgyr = allactions.Action_Radgyr()

In [66]:
# import DataSetList object to store radius of gyration data
# there is much shorter way to do this but this is for demonstration
from pytraj.DataSetList import DataSetList

# store data file for writing output
from pytraj.DataFileList import DataFileList

In [67]:
dsetlist = DataSetList()
dflist = DataFileList()
# perform action on traj

# calculate radgyr using CA, 
radgyr.read_input("radgyr @CA out test.out", current_top=traj.top, dslist=dsetlist, dflist=dflist)

0

In [68]:
# process Topology if needed
radgyr.process(traj.top)

0

In [69]:
# start looping all Frame objects

In [70]:
for idx, frame in enumerate(traj):
    radgyr.do_action(frame)

In [71]:
# it's time to get the data
import pytraj as pyc

# currently we need to cast dataset since cpptraj has several kinds
d0 = pyc.cast_dataset(dsetlist[0])
print (d0[:])

<MemoryView of 'array' object>


In [72]:
# saving to file
dflist.write_all_datafiles()

In [73]:
# make sure we already save it
!ls test.out

test.out


In [74]:
!head test.out

#Frame         radgyr  radgyr[Max]
       1      14.7456      23.7857
       2       8.4299      14.3481
       3       8.4431      14.9007
       4       8.1103      15.2074
       5       8.1008      13.5288
       6       8.9208      13.8100
       7       7.9388      12.4629
       8       8.0225      12.2434
       9       8.3950      13.7869


In [75]:
# what's happen if we get lost?
from pytraj import info
info('rms2d')