# very simple example

In [1]:
# note: the method's name might be changed in the future (that's why it starts with _)

import pytraj.io as io

In [2]:
tlist = io._iterload_from_filelist("../tests/data/Test_RemdTraj/rem.nc.*", "../tests/data/Test_RemdTraj/ala2.99sb.mbondi2.parm7")

print (tlist)

print ("")

filelist = [traj.filename for traj in tlist]
print (filelist)

[<pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           ]

['../tests/data/Test_RemdTraj/rem.nc.000', '../tests/data/Test_RemdTraj/rem.nc.001', '../tests/data/Test_RemdTraj/rem.nc.002', '../tests/data/Test_RemdTraj/rem.nc.003']


In [3]:
# we can load from a list of files too
tlist2 = io._iterload_from_filelist(filelist, "../tests/data/Test_RemdTraj/ala2.99sb.mbondi2.parm7")
print (tlist2)

[<pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           ]


In [4]:
# pytraj is smart enought to perform 'action' on a list of files too
import pytraj.common_actions as pyca

# calculate vector center of mass? (like vector between all CA atoms and all CB atoms)
dset = pyca.calc_COM(tlist2, "@CA @CB", dtype='dataset')
print (dset)
print ("number of vectors (expteced = 40) = ", dset.size)
print (dset[0])

[<pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           , <pytraj.TrajectoryIterator with 10 frames: <Topology with 1 mols, 3 residues, 22 atoms, 21 bonds, non-PBC>>
           ]
number of vectors (expteced = 40) =  40
<Vec3: 4.312386989593506 4.813084602355957 -0.13005274534225464>


In [5]:
# you love numpy. no problem 
dset.to_ndarray()[:10] # only print first 10 arrays

array([[ 4.31238699,  4.8130846 , -0.13005275],
       [ 4.70764303,  5.50276709, -0.14578578],
       [ 4.77340126,  5.08861113, -0.82117581],
       [ 4.24787378,  4.67501116, -0.68110001],
       [ 4.74331141,  4.12898731, -1.65600121],
       [ 4.6513381 ,  4.12851858, -1.41458416],
       [ 5.34591913,  5.18222713, -1.85356557],
       [ 4.95888329,  4.6319623 , -1.85287309],
       [ 5.237041  ,  3.9452877 , -1.49205673],
       [ 4.86035633,  3.81905341, -0.93039691]])

# more complicated example

In [6]:
import pytraj.io as io

!ls ../tests/data/nogit/remd/remd.x.* |wc
!du -sh ../tests/data/nogit/remd/remd.x.* |head -5

     40      40    1440
200M	../tests/data/nogit/remd/remd.x.000
200M	../tests/data/nogit/remd/remd.x.001
200M	../tests/data/nogit/remd/remd.x.002
200M	../tests/data/nogit/remd/remd.x.003
200M	../tests/data/nogit/remd/remd.x.004


In [7]:
!ls ../tests/data/nogit/remd/remd.x* | head 

../tests/data/nogit/remd/remd.x.000
../tests/data/nogit/remd/remd.x.001
../tests/data/nogit/remd/remd.x.002
../tests/data/nogit/remd/remd.x.003
../tests/data/nogit/remd/remd.x.004
../tests/data/nogit/remd/remd.x.005
../tests/data/nogit/remd/remd.x.006
../tests/data/nogit/remd/remd.x.007
../tests/data/nogit/remd/remd.x.008
../tests/data/nogit/remd/remd.x.009


In [8]:
# try to load a list of 40 replica trajectories, 200 Mb/each (8 Gb total). Since we have very large trajs, we need to use 
# iterload

trajlist = io._iterload_from_filelist("../tests/data/nogit/remd/remd.x.*", "../tests/data/nogit/remd/myparm.parm7")
print (trajlist[:10]) # print only first 10 replicas

[<pytraj.TrajectoryIterator with 1000 frames: <Topology with 5634 mols, 5666 residues, 17443 atoms, 17452 bonds, PBC with box type = truncoct>>
           , <pytraj.TrajectoryIterator with 1000 frames: <Topology with 5634 mols, 5666 residues, 17443 atoms, 17452 bonds, PBC with box type = truncoct>>
           , <pytraj.TrajectoryIterator with 1000 frames: <Topology with 5634 mols, 5666 residues, 17443 atoms, 17452 bonds, PBC with box type = truncoct>>
           , <pytraj.TrajectoryIterator with 1000 frames: <Topology with 5634 mols, 5666 residues, 17443 atoms, 17452 bonds, PBC with box type = truncoct>>
           , <pytraj.TrajectoryIterator with 1000 frames: <Topology with 5634 mols, 5666 residues, 17443 atoms, 17452 bonds, PBC with box type = truncoct>>
           , <pytraj.TrajectoryIterator with 1000 frames: <Topology with 5634 mols, 5666 residues, 17443 atoms, 17452 bonds, PBC with box type = truncoct>>
           , <pytraj.TrajectoryIterator with 1000 frames: <Topology with 563

In [9]:
# but we are usually not interested in all frames, let's create a new list by skipping every 100 frames
tlist2 = [traj(0, 999, 100) for traj in trajlist]

print (tlist2[:10])

[<generator object frame_iter at 0x2aaac8ad0b40>, <generator object frame_iter at 0x2aaac8ad0f30>, <generator object frame_iter at 0x2aaac8ad07e0>, <generator object frame_iter at 0x2aaac8ad0ee8>, <generator object frame_iter at 0x2aaac8ad0ea0>, <generator object frame_iter at 0x2aaac8ad0e58>, <generator object frame_iter at 0x2aaac8ad0e10>, <generator object frame_iter at 0x2aaac8ad0900>, <generator object frame_iter at 0x2aaac8ad0870>, <generator object frame_iter at 0x2aaac8ad0708>]


In [10]:
# we can use `_frame_iter_master to asscess Frame from `tlist2`

from pytraj import Frame
from pytraj._shared_methods import _frame_iter_master

for frame in _frame_iter_master(tlist2):
    assert isinstance(frame, Frame) # make sure we get Frame object
print (frame)

<Frame with 17443 atoms>


In [11]:
# we can perform Action for `tlist2` too. For example. calculate distance

import pytraj.common_actions as pyca
top = trajlist[0].top
print (top) # 

# since we already iterated a list of frame iterators before, we need to "rewind" it.
tlist2 = [traj(0, 999, 100) for traj in trajlist]

d = pyca.calc_COM(_frame_iter_master(tlist2), "@CB @CA", top=top) 
# need to provide `top` since tlist2 is just a list of frame_iter, it does not have topology info
print (d.size)
print (d.to_ndarray())

<Topology with 5634 mols, 5666 residues, 17443 atoms, 17452 bonds, PBC with box type = truncoct>
400
[[-16.17566739   5.14547523   6.08436034]
 [ 15.65815553  26.40960922  15.48960314]
 [ 11.01263669  18.25198135  -2.60711711]
 ..., 
 [ 28.34306431   8.78684195  14.80370186]
 [-14.69444676  26.15370248   2.35538592]
 [ 13.62363661 -26.57976847  -0.47856472]]
