pytraj (and cpptraj) does not depend on numpy/scipy library. However you are still able to fully use their computational power by using memoryview in Python

In [1]:
from __future__ import absolute_import
from pytraj import load_sample_data

In [2]:
# load sample Ala3 trajectory 
traj = load_sample_data()

# extract frame object
frame = traj[0]

In [3]:
# using memoryview with numpy array (basically you can use numpy to change 
# frame object's internal data without doing extra copying)

import numpy as np

arr0 = np.asarray(frame[:])
# or explicitly use frame.buffer3d
# arr0 = np.asarray(frame.buffer3d[:])

print (frame.shape)
print (arr0.shape)

(34, 3)
(34, 3)


In [4]:
# update arr0 will update frame's coordinates too
print ("before updating arr0")
print (frame[0, :])
print (arr0[0, :])

arr0[0, :] = np.arange(3, dtype=np.float64)
print ()
print ("after updating arr0")
print (frame[0, :])
print (arr0[0, :])

before updating arr0
[  3.32577000e+00   1.54790900e+00  -1.60000000e-06]
[  3.32577000e+00   1.54790900e+00  -1.60000000e-06]

after updating arr0
[ 0.  1.  2.]
[ 0.  1.  2.]


In [5]:
# update all x-coords
arr0[:, 0] = np.zeros(traj.n_atoms) # dummy test

In [6]:
arr0

array([[  0.00000000e+00,   1.00000000e+00,   2.00000000e+00],
       [  0.00000000e+00,   8.39991000e-01,  -2.90000000e-06],
       [  0.00000000e+00,   1.49950800e+00,  -8.74687000e-01],
       [  0.00000000e+00,   1.49950700e+00,   8.74685000e-01],
       [  0.00000000e+00,   2.84579500e+00,  -1.00000000e-07],
       [  0.00000000e+00,   3.40012900e+00,  -8.89820000e-01],
       [  0.00000000e+00,   3.65383800e+00,   1.23214300e+00],
       [  0.00000000e+00,   3.11579500e+00,   2.13119700e+00],
       [  0.00000000e+00,   4.62301700e+00,   1.20578600e+00],
       [  0.00000000e+00,   3.80107500e+00,   1.24137900e+00],
       [  0.00000000e+00,   2.70520700e+00,  -4.40000000e-06],
       [  0.00000000e+00,   1.59317500e+00,  -8.40000000e-06],
       [  0.00000000e+00,   3.83858360e+00,  -5.10000000e-06],
       [  0.00000000e+00,   4.72953230e+00,  -2.80000000e-06],
       [  0.00000000e+00,   3.83858370e+00,  -7.40000000e-06],
       [  0.00000000e+00,   3.32483910e+00,   8.8981180

In [7]:
frame[:, 0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])